### ISSUE TITLE
Issues generating look up table

### ISSUE THREAD

**Issue by Helioviewer-Kirill** [mjpauly/aia#1]
Hello,

Thanks for your work on this repo!
I'm planning to use this rescaling data to apply a brightness correction to AIA images on helioviewer.

Unfortunately, the data available in this repo is over 2 years old and I'm having an issue regenerating it using the sun_intensity.py script.

I get the following stack trace when executing sun_intensity.py with up to date sunpy and astropy-3.2.1 on python 3.6.8

```
Traceback (most recent call last):
  File "sun_intensity.py", line 342, in <module>
    df = update_csv()
  File "sun_intensity.py", line 256, in update_csv
    df = main_no_mp()
  File "sun_intensity.py", line 221, in main_no_mp
    r = process_wave(wave)
  File "sun_intensity.py", line 161, in process_wave
    while no_images(fles):
  File "sun_intensity.py", line 134, in no_images
    out = out or getFitsHdr(fles[0])['quality'] != 0
  File "sun_intensity.py", line 66, in getFitsHdr
    f = fits.open(fle)
  File "/home/helioviewer/.local/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 151, in fitsopen
    lazy_load_hdus, **kwargs)
  File "/home/helioviewer/.local/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 390, in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)
  File "/home/helioviewer/.local/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 1039, in _readfrom
    fileobj = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
  File "/home/helioviewer/.local/lib/python3.6/site-packages/astropy/utils/decorators.py", line 521, in wrapper
    return function(*args, **kwargs)
  File "/home/helioviewer/.local/lib/python3.6/site-packages/astropy/io/fits/file.py", line 178, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/home/helioviewer/.local/lib/python3.6/site-packages/astropy/io/fits/file.py", line 555, in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
  File "/home/helioviewer/.local/lib/python3.6/site-packages/astropy/io/fits/util.py", line 397, in fileobj_open
    return open(filename, mode, buffering=0)
FileNotFoundError: [Errno 2] No such file or directory: '/SUM80/D184468329/S00000/image_lev1.fits'
```

Does this code download the images to analyze first, or is there something else I should be doing to get these images before starting this process?

Thanks!

**Comment by mjpauly** [comment]
Hi! When I wrote this code at LMSAL, I had direct access to the level 1 fits files on my work station, so the code doesn't download the files. It currently just looks up the list of filenames that match a search query, then tries to use them.

However, it should be fairly straightforward to modify it to download the files you want using [Sunpy to query JSOC](https://docs.sunpy.org/en/stable/guide/acquiring_data/jsoc.html#querying-the-jsoc). Modifying the code at [this point](https://github.com/mjpauly/aia/blob/25b6794abeaf8058771bf692301e07a442099f50/sun_intensity.py#L159) seems reasonable.

There might even be a simpler way to query JSOC directly since you already have the filenames you want to download, though I'm not quite sure how you would do it yet. Poking around [here](http://jsoc.stanford.edu/jsocwiki/FrontPage) might yield some answers.

Good luck! I'm sorry I didn't write it to be more portable originally.

**Comment by Helioviewer-Kirill** [comment]
Thanks for the reply, I'll take a look into how we can modify your code to automatically download the fits files.
